sudo: required

services:
  - docker

install:
  - docker build -t dockertestimage .

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run -e ci_env -ti dockertestimage /bin/bash -c
      "cd oommfodt &&
      python3 -m pytest --cov=oommfodt --cov-config .coveragerc &&
      bash <(curl -s https://codecov.io/bash) -t dee03a75-54f6-4959-8fe3-0ccf993a8374"

notifications:
  slack: joommf:eqKxGPXuUP3LxnOfxg7GWgDF