language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"
# Install any dependencies for running the tests:
install: pip install codecov pytest-cov pandas
# command to run tests
script:
  py.test --cov=oommfodt --cov-config .coveragerc
after_success:
  codecov